### ISSUE TITLE
ModuleNotFoundError: No module named 'wordpress'

### ISSUE THREAD

**Issue by ghost** [swappsco/django-wordpress-api#11]
* Django Wordpress API version: commit 856ab95ce83345e21f801d59967d3afb6bdf9250
* Django version: 3.0.5
* Python version: 3.6
* Operating System: Windows 10

### Description

Tried to run the example as described example/README.md, but get an error.
I cloned the repository, installed the requirements.txt in example folder referring to requirements_test.txt in the root folder.
Then I tried running `python manage.py makemigrations` and get the error 
ModuleNotFoundError: No module named 'wordpress'

Full traceback is here:
```
Traceback (most recent call last):
  File "C:/Users/Frost/Downloads/wp-djang/django-wordpress-api/example/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 366, in execute
    self.check()
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Frost\Downloads\wp-djang\django-wordpress-api\example\example\urls.py", line 22, in <module>
    url(r'', include('wordpress.urls', namespace='wordpress')),
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Frost\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'wordpress'
```

Process finished with exit code 1

**Comment by ghost** [comment]
I figured I would append a copy of `pip freeze`
[installed-packages.txt](https://github.com/swappsco/django-wordpress-api/files/4512212/installed-packages.txt)
